name: California Fresh Food
favicon: null
layout_spectrum: 0.29868444544263184
typography_spectrum: 0.34612145368009806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c9cac2'
    - '#7a7974'
    - '#424236'
    - '#d4943c'
  brandStrength: 0.5376467301975936
  lightness: 0.8063142930623144
  saturation: 0.8258358454331756
  rhythmicContrast: 0.7730679707601666
purpose: []
